<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Content\**" />
    <Content Remove="wwwroot\Content\**" />
    <EmbeddedResource Remove="wwwroot\Content\**" />
    <None Remove="wwwroot\Content\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccAddressInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccAmenitiesInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccAvailableInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccBedInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccBuildingSizeInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccCapacityInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccCounterBox.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccElevatorPart.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccFloorInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccLandAreaInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccMetaTitleDescInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccOwnershipInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccParkingInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccPhotoInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccPositionInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccPriceInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccPriceInputItem.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccRoomInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccRulesInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccTitleDescInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AccTypeInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_AdminPhotoInput.cshtml" />
    <None Include="Views\Accomodation\AddEditFormInputs\_ComplexTypeInput.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageAddress.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageAmenities.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageBasicInfo.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageComments.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPagePrice.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageRelatedLinks.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageRules.cshtml" />
    <None Include="Views\Accomodation\AccPagePartials\_AccPageStatistics.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveBasicInfo.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveComplexApartment.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveComplexHouse.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveComplexHut.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveComplexSuit.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveComplexVilla.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveDetailAmenities.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReserveMainAmenities.cshtml" />
    <None Include="Views\Accomodation\ReserveComplexPartials\_ReservePrice.cshtml" />
    <None Include="Views\ActionLog\Detail.cshtml" />
    <None Include="Views\ActionLog\Index.cshtml" />
    <None Include="Views\Admin\AdminStatistic.cshtml" />
    <None Include="Views\Admin\AdvertiseChart.cshtml" />
    <None Include="Views\Admin\Email.cshtml" />
    <None Include="Views\Admin\Home.cshtml" />
    <None Include="Views\Admin\PaymentChart.cshtml" />
    <None Include="Views\Admin\PaymentComparisonChart.cshtml" />
    <None Include="Views\Admin\ReserveFinanceChart.cshtml" />
    <None Include="Views\Admin\SendGroupNotification.cshtml" />
    <None Include="Views\Admin\SendWhatsappCoronaAdvMsg.cshtml" />
    <None Include="Views\Admin\Sms.cshtml" />
    <None Include="Views\Admin\UserChart.cshtml" />
    <None Include="Views\Advertise\Admin.cshtml" />
    <None Include="Views\Advertise\Edit.cshtml" />
    <None Include="Views\Advertise\Index.cshtml" />
    <None Include="Views\BankCard\Index.cshtml" />
    <None Include="Views\BlogPost\AddEdit.cshtml" />
    <None Include="Views\BlogPost\Index.cshtml" />
    <None Include="Views\BlogPost\_AddBlogPost.cshtml" />
    <None Include="Views\Cart\Admin.cshtml" />
    <None Include="Views\Cart\Bank.cshtml" />
    <None Include="Views\Cart\Index.cshtml" />
    <None Include="Views\Cart\PaymentIndex.cshtml" />
    <None Include="Views\Cart\PerformPay.cshtml" />
    <None Include="Views\Cart\TransactionResult.cshtml" />
    <None Include="Views\Category\DynamicEdit.cshtml" />
    <None Include="Views\Category\DynamicIndex.cshtml" />
    <None Include="Views\Category\Item.cshtml" />
    <None Include="Views\Category\SiteMap.cshtml" />
    <None Include="Views\Chat\Edit.cshtml" />
    <None Include="Views\Chat\Index.cshtml" />
    <None Include="Views\Comment\AdvertiseCommentDetail.cshtml" />
    <None Include="Views\Comment\AdvertiseCommentManager.cshtml" />
    <None Include="Views\Comment\Edit.cshtml" />
    <None Include="Views\Comment\Index.cshtml" />
    <None Include="Views\Comment\_AdvertiseCommentItem.cshtml" />
    <None Include="Views\Errors\AccessDenied.cshtml" />
    <None Include="Views\Errors\Http404.cshtml" />
    <None Include="Views\Errors\Http500.cshtml" />
    <None Include="Views\File\Edit.cshtml" />
    <None Include="Views\File\Index.cshtml" />
    <None Include="Views\File\PhotoCropper.cshtml" />
    <None Include="Views\GroupPayment\Index.cshtml" />
    <None Include="Views\GroupPayment\_GroupPaymentDetail.cshtml" />
    <None Include="Views\GroupPayment\_GroupPaymentList.cshtml" />
    <None Include="Views\Post\AccomodationManager.cshtml" />
    <None Include="Views\Post\Contact.cshtml" />
    <None Include="Views\Post\dashboard.cshtml" />
    <None Include="Views\Post\DownloadApp.cshtml" />
    <None Include="Views\Post\Edit.cshtml" />
    <None Include="Views\Post\EnamadRedirect.cshtml" />
    <None Include="Views\Post\FavoriteManager.cshtml" />
    <None Include="Views\Post\FrequentlyQuestions.cshtml" />
    <None Include="Views\Post\Index.cshtml" />
    <None Include="Views\Post\News.cshtml" />
    <None Include="Views\Post\NewsItem.cshtml" />
    <None Include="Views\Post\Page.cshtml" />
    <None Include="Views\Post\PresentAndPrize.cshtml" />
    <None Include="Views\Post\ProfileManager.cshtml" />
    <None Include="Views\Post\Public.cshtml" />
    <None Include="Views\Post\ReplyComment.cshtml" />
    <None Include="Views\Post\SamandehiRedirect.cshtml" />
    <None Include="Views\Post\Search.cshtml" />
    <None Include="Views\Post\SearchAccID.cshtml" />
    <None Include="Views\Post\_EditFast.cshtml" />
    <None Include="Views\Post\_InstantReserve.cshtml" />
    <None Include="Views\Post\_MinAndMaxDay.cshtml" />
    <None Include="Views\Post\_News.cshtml" />
    <None Include="Views\Post\_RadioButtonForm.cshtml" />
    <None Include="Views\Post\_RoomComplex.cshtml" />
    <None Include="Views\Post\_TitleBanner.cshtml" />
    <None Include="Views\Post\_TitleList.cshtml" />
    <None Include="Views\Post\_TitleRoomsCard.cshtml" />
    <None Include="Views\ReservePayment\AddEdit.cshtml" />
    <None Include="Views\ReservePayment\Index.cshtml" />
    <None Include="Views\Reserve\Admin.cshtml" />
    <None Include="Views\Reserve\Chat.cshtml" />
    <None Include="Views\Reserve\Edit.cshtml" />
    <None Include="Views\Reserve\GuestReceipt.cshtml" />
    <None Include="Views\Reserve\Index.cshtml" />
    <None Include="Views\Reserve\Invoice.cshtml" />
    <None Include="Views\Reserve\ReserveItemManager.cshtml" />
    <None Include="Views\Reserve\_AddGuestPayment.cshtml" />
    <None Include="Views\Reserve\_InvoiceItem.cshtml" />
    <None Include="Views\Reserve\_InvoicePopup.cshtml" />
    <None Include="Views\Reserve\_ReserveItem.cshtml" />
    <None Include="Views\Reserve\_ReserveList.cshtml" />
    <None Include="Views\Reserve\_ReservePayment.cshtml" />
    <None Include="Views\Service\Edit.cshtml" />
    <None Include="Views\Service\Index.cshtml" />
    <None Include="Views\SupportChat\Index.cshtml" />
    <None Include="Views\SupportChat\_ChatItem.cshtml" />
    <None Include="Views\SupportChat\_ChatItemList.cshtml" />
    <None Include="Views\SupportChat\_SupportItem.cshtml" />
    <None Include="Views\SupportChat\_SupportItemList.cshtml" />
    <None Include="Views\User\Admin.cshtml" />
    <None Include="Views\User\Edit.cshtml" />
    <None Include="Views\User\Index.cshtml" />
    <None Include="Views\User\MobileLogin.cshtml" />
    <None Include="Views\User\UserCreditManager.cshtml" />
    <None Include="Views\User\_InstantReserveConfirm.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="6.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="elmah" Version="1.2.2" />
    <PackageReference Include="Hangfire" Version="1.7.19" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.19" />
    <PackageReference Include="HangFire.Autofac" Version="2.3.1" />
    <PackageReference Include="Hangfire.Core" Version="1.7.19" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.7.19" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCaching" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="5.0.0" />
	<PackageReference Include="X.PagedList" Version="8.0.7" />
	<PackageReference Include="X.PagedList.Mvc.Core" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amlakbashi.Accounting\Amlakbashi.Accounting.csproj" />
    <ProjectReference Include="..\Amlakbashi.Application\Amlakbashi.Application.csproj" />
    <ProjectReference Include="..\Amlakbashi.Core\Amlakbashi.Core.csproj" />
    <ProjectReference Include="..\Amlakbashi.Mediator\Amlakbashi.Mediator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\Logs\" />
    <Folder Include="Logs\HangfireLogs\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\Resource\packages\jquery-mobile\images\" />
  </ItemGroup>

</Project>
