// <auto-generated />
using System;
using Amlakbashi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amlakbashi.Data.Migrations
{
    [DbContext(typeof(AmlakbashiDB))]
    [Migration("20221009083607_add-video-to-residence")]
    partial class addvideotoresidence
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Amlakbashi.Core.Entities.ActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ActionLogID")
                        .UseIdentityColumn();

                    b.Property<int>("ActionSource")
                        .HasColumnType("int");

                    b.Property<string>("CurrentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RelatedID")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("actionLogs");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Advertise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlbumPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmlakbashiScore")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<float>("AverageUsersScore")
                        .HasColumnType("real");

                    b.Property<bool?>("Balcony")
                        .HasColumnType("bit");

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<bool?>("Bathroom")
                        .HasColumnType("bit");

                    b.Property<int>("BlanketAndMattressCount")
                        .HasColumnType("int");

                    b.Property<int>("BuildingArea")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<float>("CleaningScore")
                        .HasColumnType("real");

                    b.Property<int>("CoolingSystem")
                        .HasColumnType("int");

                    b.Property<int>("CountryDirection")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoubleBedCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Elevator")
                        .HasColumnType("bit");

                    b.Property<bool>("EmptyTonight")
                        .HasColumnType("bit");

                    b.Property<int>("EuropeanToiletType")
                        .HasColumnType("int");

                    b.Property<int>("ExtraBlanketCount")
                        .HasColumnType("int");

                    b.Property<int>("ExtraCapacity")
                        .HasColumnType("int");

                    b.Property<int>("ExtraCapacityPrice")
                        .HasColumnType("int");

                    b.Property<bool?>("Filming")
                        .HasColumnType("bit");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool?>("Foosball")
                        .HasColumnType("bit");

                    b.Property<bool?>("Golf")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hairdryer")
                        .HasColumnType("bit");

                    b.Property<int>("HeatingSystem")
                        .HasColumnType("int");

                    b.Property<bool>("HideInSearch")
                        .HasColumnType("bit");

                    b.Property<int>("HolidayPrice")
                        .HasColumnType("int");

                    b.Property<int?>("HygieneProtocol")
                        .HasColumnType("int");

                    b.Property<int>("InstantReserveStatus")
                        .HasColumnType("int");

                    b.Property<bool?>("Jacuzzi")
                        .HasColumnType("bit");

                    b.Property<bool?>("KitchenHood")
                        .HasColumnType("bit");

                    b.Property<bool?>("KitchenUtensils")
                        .HasColumnType("bit");

                    b.Property<int>("LandArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("License")
                        .HasColumnType("bit");

                    b.Property<long?>("LicenseFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<long?>("MainPhotoId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxInstantReserveStartTimeInterval")
                        .HasColumnType("int");

                    b.Property<int>("MaxReserveDuration")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MicrowaveOven")
                        .HasColumnType("bit");

                    b.Property<long>("MinReserveDateForNowruz")
                        .HasColumnType("bigint");

                    b.Property<int>("MinReserveDuration")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<long>("MonthlyPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("NotVerifyReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NowruzExtraCapacityPrice")
                        .HasColumnType("int");

                    b.Property<int>("NowruzPrice")
                        .HasColumnType("int");

                    b.Property<string>("OldSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Oven")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Parking")
                        .HasColumnType("int");

                    b.Property<bool>("Party")
                        .HasColumnType("bit");

                    b.Property<int>("PeakHolidayPrice")
                        .HasColumnType("int");

                    b.Property<bool>("Pets")
                        .HasColumnType("bit");

                    b.Property<bool?>("Pool")
                        .HasColumnType("bit");

                    b.Property<int>("PoolFeatures")
                        .HasColumnType("int");

                    b.Property<bool?>("PoolTable")
                        .HasColumnType("bit");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<bool?>("Refrigerator")
                        .HasColumnType("bit");

                    b.Property<string>("RegionsPersianTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredEvidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResidenceScore")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Sauna")
                        .HasColumnType("bit");

                    b.Property<int>("SingleBedCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Smoking")
                        .HasColumnType("bit");

                    b.Property<bool?>("SoundSystem")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupportDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TV")
                        .HasColumnType("bit");

                    b.Property<bool?>("TeaMaker")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<int>("UnitCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long?>("VideoId")
                        .HasColumnType("bigint");

                    b.Property<byte>("VideoStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.Property<int>("VillaType")
                        .HasColumnType("int");

                    b.Property<int>("WC")
                        .HasColumnType("int");

                    b.Property<bool?>("WashingMachine")
                        .HasColumnType("bit");

                    b.Property<bool?>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CityId");

                    b.HasIndex("LicenseFileId")
                        .IsUnique()
                        .HasFilter("[LicenseFileId] IS NOT NULL");

                    b.HasIndex("MainPhotoId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasFilter("[VideoId] IS NOT NULL");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.AdvertiseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("ReasonString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.ToTable("AdvertiseReports");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BankCardID")
                        .UseIdentityColumn();

                    b.Property<string>("BankCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankCardStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShabaStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccommodationType")
                        .HasColumnType("int");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("BlogLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifyUserID")
                        .HasColumnType("int");

                    b.Property<long>("PhotoID")
                        .HasColumnType("bigint");

                    b.Property<int>("PoolStatus")
                        .HasColumnType("int");

                    b.Property<int>("PositionType")
                        .HasColumnType("int");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<int>("ShowingPlace")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CartID")
                        .UseIdentityColumn();

                    b.Property<long?>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<int>("AmlakID")
                        .HasColumnType("int");

                    b.Property<int>("BannerID")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("Payment_PaymentID");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReserveID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ChatID")
                        .UseIdentityColumn();

                    b.Property<int>("ChatStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReadStatus")
                        .HasColumnType("int");

                    b.Property<long>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<int>("SupportReadStatus")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReserveID");

                    b.HasIndex("UserID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CommentID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<long?>("HostReplyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifyDatetick")
                        .HasColumnType("bigint");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorID")
                        .HasColumnType("int");

                    b.Property<long?>("ParentID")
                        .HasColumnType("bigint");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.Property<int?>("RecieverUserID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("SeenByHost")
                        .HasColumnType("bit");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SuspendReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("HostReplyId");

                    b.HasIndex("OperatorID");

                    b.HasIndex("ParentID");

                    b.HasIndex("RecieverUserID");

                    b.HasIndex("SenderUserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.CreditTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<long>("BankTransactionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedWalletTransactionId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("Amount");

                    b.Property<long>("RemainedPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("WalletRemainingAmount");

                    b.Property<long?>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionCause")
                        .HasColumnType("int")
                        .HasColumnName("Reason");

                    b.Property<string>("TransactionCauseString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedWalletTransactionId")
                        .IsUnique()
                        .HasFilter("[ModifiedWalletTransactionId] IS NOT NULL");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReserveID");

                    b.HasIndex("UserID");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DiscountCoupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<int>("PresentorUserID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<long>("UsingReserveID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("DiscountCoupons");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DiscountTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiscountTableID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.ToTable("DiscountTables");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DynamicCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID")
                        .UseIdentityColumn();

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<string>("AreaStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryPostID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryPostText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryPostTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("City")
                        .HasColumnType("int");

                    b.Property<string>("CityAreaListString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountAcc")
                        .HasColumnType("int");

                    b.Property<int>("CountAdvertise")
                        .HasColumnType("int");

                    b.Property<int>("CountView")
                        .HasColumnType("int");

                    b.Property<int>("CountryDirection")
                        .HasColumnType("int");

                    b.Property<string>("CustomUrlTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionH1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaxPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MinPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("MostAccType")
                        .HasColumnType("int");

                    b.Property<int>("OldCountView")
                        .HasColumnType("int");

                    b.Property<int>("ParentAccType")
                        .HasColumnType("int");

                    b.Property<int>("ParentCountAcc")
                        .HasColumnType("int");

                    b.Property<int>("ParentMaxPrice")
                        .HasColumnType("int");

                    b.Property<int>("ParentMinPrice")
                        .HasColumnType("int");

                    b.Property<string>("ParentRegionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Province")
                        .HasColumnType("int");

                    b.Property<string>("RegionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCategoryIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelatedItemsBehaviour")
                        .HasColumnType("int");

                    b.Property<bool>("ShowDescription")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("City");

                    b.HasIndex("Province");

                    b.ToTable("DynamicCategories");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ExtrinsicReserve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NotifierUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("HostUserID");

                    b.HasIndex("NotifierUserID");

                    b.ToTable("ExtrinsicReserves");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("FileID")
                        .UseIdentityColumn();

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinifyMaxWidth")
                        .HasColumnType("int");

                    b.Property<long>("MinifyQualityPercent")
                        .HasColumnType("bigint");

                    b.Property<int>("MinifyStatus")
                        .HasColumnType("int");

                    b.Property<int>("MinifyStatusInt")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.GroupPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupPaymentID")
                        .UseIdentityColumn();

                    b.Property<int>("CountFailedPayments")
                        .HasColumnType("int");

                    b.Property<int>("CountPayments")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<long>("PaidPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayListUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayResultUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReserveIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusInt")
                        .HasColumnType("int");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GroupPayments");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.InstantReserveAutoCancel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Force")
                        .HasColumnType("bit");

                    b.Property<long>("ReserveId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SendSms")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InstantReserveAutoCancels");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.InstantReserveDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<long>("ResidenceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResidenceId");

                    b.ToTable("InstantReserveDate");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.OccupiedTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OccupiedTableID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<long?>("ExtrinsicReserveID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ReserveID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("ExtrinsicReserveID");

                    b.HasIndex("ReserveID");

                    b.ToTable("OccupiedTables");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("Bank")
                        .HasColumnType("int");

                    b.Property<long>("CouponID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PrizePrice")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReferenceNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReservePaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservePrice")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TraceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<long?>("WalletTransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReserveID");

                    b.HasIndex("ReservePaymentId");

                    b.HasIndex("UserID");

                    b.HasIndex("WalletTransactionId")
                        .IsUnique()
                        .HasFilter("[WalletTransactionId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PostID")
                        .UseIdentityColumn();

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhotoID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.PriceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PriceTableID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long>("UnixDate")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.ToTable("PriceTables");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.PrizeCreditTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("CustomTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<long>("RemainedPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReserveID");

                    b.HasIndex("UserID");

                    b.ToTable("PrizeCreditTransactions");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegionID")
                        .UseIdentityColumn();

                    b.Property<int>("CountAdvertise")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("PersianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Related")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReportItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReportItemID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifyDatetick")
                        .HasColumnType("bigint");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("UserID");

                    b.ToTable("ReportItems");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Reserve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<bool>("AccVisitedByGuest")
                        .HasColumnType("bit")
                        .HasColumnName("VisitResidenceByGuest");

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint")
                        .HasColumnName("ResidenceId");

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelDiscussion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CancelState")
                        .HasColumnType("int");

                    b.Property<long>("CouponCalculationPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("CouponID")
                        .HasColumnType("bigint")
                        .HasColumnName("CouponId");

                    b.Property<long>("CouponPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DepositPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("DisableAutoCancel")
                        .HasColumnType("bit");

                    b.Property<int>("EarlyCheckoutStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestCallState")
                        .HasColumnType("int");

                    b.Property<int>("HostCallState")
                        .HasColumnType("int");

                    b.Property<int>("HostResponse")
                        .HasColumnType("int");

                    b.Property<DateTime>("HostResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostUserID")
                        .HasColumnType("int")
                        .HasColumnName("HostId");

                    b.Property<bool>("InstantReserve")
                        .HasColumnType("bit");

                    b.Property<bool>("InstantReserveCancelHost")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<bool>("PaymentGTAGRegistered")
                        .HasColumnType("bit");

                    b.Property<long>("PrizePrice")
                        .HasColumnType("bigint");

                    b.Property<long>("PrizeTransactionID")
                        .HasColumnType("bigint")
                        .HasColumnName("PrizeTransactionId");

                    b.Property<bool>("RatingShownToGuest")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupportInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("GuestId");

                    b.Property<bool>("shouldFollow")
                        .HasColumnType("bit")
                        .HasColumnName("ShouldFollowUp");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseID");

                    b.HasIndex("HostUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReserveAutoCancel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Force")
                        .HasColumnType("bit");

                    b.Property<long>("ReserveId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SendSms")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReserveAutoCancels");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReservePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<long>("RefID")
                        .HasColumnType("bigint");

                    b.Property<long>("ReserveID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TransactionID")
                        .HasColumnType("bigint");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReserveID");

                    b.HasIndex("UserID");

                    b.ToTable("ReservePayments");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReserveSendSms", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("advertise_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("audience_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cause_string")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doer_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extra_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extra_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extra_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("initial")
                        .HasColumnType("bit");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remain_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reserve_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReserveSendSms");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReserveSupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReserveSupportID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JourneyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSupporterActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservesSimilar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservesSupporting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservesWaitingForSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupporterID")
                        .HasColumnType("int");

                    b.Property<string>("TransferReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestID");

                    b.HasIndex("SupporterID");

                    b.ToTable("ReserveSupports");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ServicePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServicePostID")
                        .UseIdentityColumn();

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServicePosts");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SettingID")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.SupportChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMessageTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupporterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupporterID");

                    b.HasIndex("UserID");

                    b.ToTable("SupportChats");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.SupportChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReadStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReadStatusInt")
                        .HasColumnType("int");

                    b.Property<long>("SupportChatID")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("TypeInt")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupportChatID");

                    b.HasIndex("UserID");

                    b.ToTable("SupportChatMessages");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AmlakbashiScore")
                        .HasColumnType("int");

                    b.Property<string>("AppNotificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableInstantReserve")
                        .HasColumnType("bit");

                    b.Property<string>("FcmAppNotificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForbiddenRegionsAccess")
                        .HasColumnType("bit");

                    b.Property<long>("GiftWalletAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LandlinePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastNotifPermitionTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("NoticesPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("NotificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerShip")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PhotoID")
                        .HasColumnType("bigint");

                    b.Property<int>("PhotoStatus")
                        .HasColumnType("int");

                    b.Property<bool>("PresentorPrizeGiven")
                        .HasColumnType("bit");

                    b.Property<int>("PresentorUserID")
                        .HasColumnType("int");

                    b.Property<bool>("RecieveAppreciateDiscount")
                        .HasColumnType("bit");

                    b.Property<string>("ThirdPersonPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserScore")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PhotoID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavoriteID")
                        .UseIdentityColumn();

                    b.Property<long>("AdvertiseID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("DynamicCategoryAdvertises", b =>
                {
                    b.Property<long>("Advertise_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("DynamicCategory_Id")
                        .HasColumnType("int");

                    b.HasKey("Advertise_Id", "DynamicCategory_Id");

                    b.HasIndex("DynamicCategory_Id");

                    b.ToTable("DynamicCategoryAdvertises");
                });

            modelBuilder.Entity("FileAdvertises", b =>
                {
                    b.Property<long>("Advertise_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("File_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Advertise_Id", "File_Id");

                    b.HasIndex("File_Id");

                    b.ToTable("FileAdvertises");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ActionLog", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Advertise", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionArea")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionCity")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Amlakbashi.Core.Entities.File", "LicenseFile")
                        .WithOne("AdvertiseLicense")
                        .HasForeignKey("Amlakbashi.Core.Entities.Advertise", "LicenseFileId");

                    b.HasOne("Amlakbashi.Core.Entities.File", "MainPhoto")
                        .WithMany("MainPhotos")
                        .HasForeignKey("MainPhotoId");

                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");

                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionProvince")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("Advertises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.File", "Video")
                        .WithOne("ResidenceVideo")
                        .HasForeignKey("Amlakbashi.Core.Entities.Advertise", "VideoId");

                    b.Navigation("LicenseFile");

                    b.Navigation("MainPhoto");

                    b.Navigation("Parent");

                    b.Navigation("RegionArea");

                    b.Navigation("RegionCity");

                    b.Navigation("RegionProvince");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.AdvertiseReport", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("AdvertiseReports")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.BankCard", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("BankCards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.BlogPost", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("BlogPosts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Cart", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("Carts")
                        .HasForeignKey("AdvertiseID");

                    b.HasOne("Amlakbashi.Core.Entities.Payment", "Payment")
                        .WithMany("Carts")
                        .HasForeignKey("PaymentId");

                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("Carts")
                        .HasForeignKey("ReserveID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("Payment");

                    b.Navigation("Reserve");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Chat", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("Chats")
                        .HasForeignKey("ReserveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserve");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Comment", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("Comments")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.Comment", "HostReply")
                        .WithMany()
                        .HasForeignKey("HostReplyId");

                    b.HasOne("Amlakbashi.Core.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorID");

                    b.HasOne("Amlakbashi.Core.Entities.Comment", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "RecieverUser")
                        .WithMany()
                        .HasForeignKey("RecieverUserID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("HostReply");

                    b.Navigation("Operator");

                    b.Navigation("Parent");

                    b.Navigation("RecieverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.CreditTransaction", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.CreditTransaction", "ModifiedWalletTransaction")
                        .WithOne("CorrectiveWalletTransaction")
                        .HasForeignKey("Amlakbashi.Core.Entities.CreditTransaction", "ModifiedWalletTransactionId");

                    b.HasOne("Amlakbashi.Core.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("ReserveID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedWalletTransaction");

                    b.Navigation("Payment");

                    b.Navigation("Reserve");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DiscountCoupon", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("DiscountCoupons")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DiscountTable", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("DiscountTables")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.DynamicCategory", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionArea")
                        .WithMany()
                        .HasForeignKey("Area");

                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionCity")
                        .WithMany()
                        .HasForeignKey("City");

                    b.HasOne("Amlakbashi.Core.Entities.Region", "RegionProvince")
                        .WithMany()
                        .HasForeignKey("Province");

                    b.Navigation("RegionArea");

                    b.Navigation("RegionCity");

                    b.Navigation("RegionProvince");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ExtrinsicReserve", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("ExtrinsicReserves")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "NotifierUser")
                        .WithMany()
                        .HasForeignKey("NotifierUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("HostUser");

                    b.Navigation("NotifierUser");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.InstantReserveDate", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Residence")
                        .WithMany("InstantReserveDates")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.OccupiedTable", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("OccupiedTables")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.ExtrinsicReserve", "ExtrinsicReserve")
                        .WithMany()
                        .HasForeignKey("ExtrinsicReserveID");

                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany()
                        .HasForeignKey("ReserveID");

                    b.Navigation("Advertise");

                    b.Navigation("ExtrinsicReserve");

                    b.Navigation("Reserve");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Payment", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("Payments")
                        .HasForeignKey("ReserveID");

                    b.HasOne("Amlakbashi.Core.Entities.ReservePayment", "ReservePayment")
                        .WithMany()
                        .HasForeignKey("ReservePaymentId");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.CreditTransaction", "CreditTransaction")
                        .WithOne()
                        .HasForeignKey("Amlakbashi.Core.Entities.Payment", "WalletTransactionId");

                    b.Navigation("CreditTransaction");

                    b.Navigation("Reserve");

                    b.Navigation("ReservePayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.PriceTable", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("PriceTables")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.PrizeCreditTransaction", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("PrizeCreditTransactions")
                        .HasForeignKey("ReserveID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("PrizeCreditTransactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserve");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Region", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Region", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReportItem", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("ReportItems")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Reserve", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", "Advertise")
                        .WithMany("Reserves")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "HostUser")
                        .WithMany("HostReserves")
                        .HasForeignKey("HostUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "GuestUser")
                        .WithMany("Reserves")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("GuestUser");

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReservePayment", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("Amlakbashi.Core.Entities.Reserve", "Reserve")
                        .WithMany("ReservePayments")
                        .HasForeignKey("ReserveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Reserve");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.ReserveSupport", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "Guest")
                        .WithMany("ReserveSupportsAsGuest")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "Supporter")
                        .WithMany("ReserveSupportsAsSupporter")
                        .HasForeignKey("SupporterID");

                    b.Navigation("Guest");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.SupportChat", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterID");

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Supporter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.SupportChatMessage", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.SupportChat", "SupportChat")
                        .WithMany("Messages")
                        .HasForeignKey("SupportChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("SupportChat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.User", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.File", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoID");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.User", "User")
                        .WithMany("Favorite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DynamicCategoryAdvertises", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", null)
                        .WithMany()
                        .HasForeignKey("Advertise_Id")
                        .HasConstraintName("FK_DynamicCategoryAdvertises_Residences_Advertise_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.DynamicCategory", null)
                        .WithMany()
                        .HasForeignKey("DynamicCategory_Id")
                        .HasConstraintName("FK_dbo.DynamicCategoryAdvertises_dbo.DynamicCategories_DynamicCategory_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileAdvertises", b =>
                {
                    b.HasOne("Amlakbashi.Core.Entities.Advertise", null)
                        .WithMany()
                        .HasForeignKey("Advertise_Id")
                        .HasConstraintName("FK_FileAdvertises_Residences_Advertise_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amlakbashi.Core.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("File_Id")
                        .HasConstraintName("FK_dbo.FileAdvertises_dbo.Files_File_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Advertise", b =>
                {
                    b.Navigation("AdvertiseReports");

                    b.Navigation("Carts");

                    b.Navigation("Childs");

                    b.Navigation("Comments");

                    b.Navigation("DiscountTables");

                    b.Navigation("ExtrinsicReserves");

                    b.Navigation("InstantReserveDates");

                    b.Navigation("OccupiedTables");

                    b.Navigation("PriceTables");

                    b.Navigation("ReportItems");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Comment", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.CreditTransaction", b =>
                {
                    b.Navigation("CorrectiveWalletTransaction");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.File", b =>
                {
                    b.Navigation("AdvertiseLicense");

                    b.Navigation("MainPhotos");

                    b.Navigation("ResidenceVideo");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Payment", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Region", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.Reserve", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Chats");

                    b.Navigation("CreditTransactions");

                    b.Navigation("Payments");

                    b.Navigation("PrizeCreditTransactions");

                    b.Navigation("ReservePayments");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.SupportChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Amlakbashi.Core.Entities.User", b =>
                {
                    b.Navigation("Advertises");

                    b.Navigation("BankCards");

                    b.Navigation("BlogPosts");

                    b.Navigation("Carts");

                    b.Navigation("Chats");

                    b.Navigation("CreditTransactions");

                    b.Navigation("DiscountCoupons");

                    b.Navigation("Favorite");

                    b.Navigation("HostReserves");

                    b.Navigation("Payments");

                    b.Navigation("PrizeCreditTransactions");

                    b.Navigation("Reserves");

                    b.Navigation("ReserveSupportsAsGuest");

                    b.Navigation("ReserveSupportsAsSupporter");
                });
#pragma warning restore 612, 618
        }
    }
}
