using System.Collections.Generic;

namespace Amlakbashi.Core.Identity
{
    public static class PolicyData
    {
        public static Dictionary<string, string[]> AllPolicies
        {
            get
            {
                return new Dictionary<string, string[]>
                {
                    {
                        Policies.Admin_General,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Reserve_View,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Post_View,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Roles_View,
                        new string[]
                        {
                            Roles.SuperAdmin
                        }
                    },
                    {
                        Policies.Roles_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin
                        }
                    },
                    {
                        Policies.Advertise_View,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Advertise_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.ReserveJunior,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.AdvertiseJunior,
                            Roles.ContentManager,
                            Roles.ContentSenior
                        }
                    },
                    {
                        Policies.Advertise_Publish,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior
                        }
                    },
                    {
                        Policies.Advertise_Url_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.AdvertiseManager
                        }
                    },
                    {
                        Policies.Category_View,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.AdvertiseJunior,
                            Roles.ContentManager,
                            Roles.ContentSenior
                        }
                    },
                    {
                        Policies.Category_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.AdvertiseManager,
                            Roles.ContentManager
                        }
                    },
                    {
                        Policies.Reserve_Support_Actions,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Reserve_Payment_Actions,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.FinanceJunior
                        }
                    },
                    {
                        Policies.Reserve_Payment_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.FinanceJunior
                        }
                    },
                    {
                        Policies.Reserve_Payment_Add,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.FinanceJunior
                        }
                    },
                    {
                        Policies.Reserve_Edit_Price,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior
                        }
                    },
                    {
                        Policies.Reserve_Edit_Normal,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.FinanceManager
                        }
                    },
                    {
                        Policies.Reserve_Edit_Reserved,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.FinanceManager
                        }
                    },
                    {
                        Policies.User_Host_Support,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.UserManager
                        }
                    },
                    {
                        Policies.User_General_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.UserManager,
                            Roles.UserSenior,
                            Roles.UserJunior,
                            Roles.ReserveSenior,
                            Roles.ReserveManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.ContentManager,
                            Roles.ContentSenior,
                            Roles.CommunicationManager,
                            Roles.CommunicationSenior,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior
                        }
                    },
                    {
                        Policies.User_Identity_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.AdvertiseManager,
                            Roles.UserManager,
                            Roles.UserSenior
                        }
                    },
                    {
                        Policies.User_Contact_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.CommunicationManager,
                            Roles.CommunicationSenior,
                            Roles.UserManager,
                            Roles.UserSenior,
                            Roles.UserJunior
                        }
                    },
                    {
                        Policies.User_PFP_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.ContentManager,
                            Roles.CommunicationManager,
                            Roles.UserManager,
                            Roles.UserSenior,
                            Roles.UserJunior
                        }
                    },
                    {
                        Policies.User_Credit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.AdvertiseManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.UserManager
                        }
                    },
                    {
                        Policies.User_Bank_Info,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.ReserveManager,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.FinanceJunior,
                            Roles.UserManager,
                            Roles.UserSenior
                        }
                    },
                    {
                        Policies.User_Access_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.AdvertiseManager,
                            Roles.FinanceManager,
                            Roles.UserManager,
                            Roles.UserSenior,
                            Roles.UserJunior
                        }
                    },
                    {
                        Policies.User_Impersonate,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.User_Support_Chat,
                        Roles.AllEmployeeRoles
                    },
                    {
                        Policies.Statistics_View,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior
                        }
                    },
                    {
                        Policies.Send_Message_To_Users,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.CommunicationManager,
                            Roles.CommunicationSenior,
                            Roles.UserManager
                        }
                    },
                    {
                        Policies.ActionLog_View,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.AdvertiseManager,
                            Roles.AdvertiseSenior,
                            Roles.ContentManager,
                            Roles.CommunicationManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.UserManager,
                            Roles.UserSenior
                        }
                    },
                    {
                        Policies.Post_Add,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ContentManager,
                            Roles.ContentSenior
                        }
                    },
                    {
                        Policies.Post_Publish,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ContentManager
                        }
                    },
                    {
                        Policies.Post_Edit,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ContentManager,
                            Roles.ContentSenior
                        }
                    },
                    {
                        Policies.Payment_View,
                        new string[]
                        {
                            Roles.SuperAdmin,
                            Roles.Admin,
                            Roles.TechnicalManager,
                            Roles.TechnicalEmployee,
                            Roles.ReserveManager,
                            Roles.ReserveSenior,
                            Roles.AdvertiseManager,
                            Roles.FinanceManager,
                            Roles.FinanceSenior,
                            Roles.FinanceJunior
                        }
                    },
                };
            }
        }
    }
}
